<?xml version="1.0" ?>
<package format="3">
  <name>kinova_gen3_hw</name>
  <version>5.1.0</version>

  <description>
    Hardware configuration for a Kinova Gen3 7DoF arm running on the real Kortex
    driver. Inherits from kinova_gen3_sim and overrides only the
    hardware-specific fields.
  </description>

  <maintainer email="david.yackzan@picknik.ai">David Yackzan</maintainer>
  <maintainer email="paul.gesel@picknik.ai">Paul Gesel</maintainer>

  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>kinova_gen3_sim</depend>

  <exec_depend>kinova_pstop_manager</exec_depend>
  <exec_depend>kinova_vision</exec_depend>
  <exec_depend>kortex_driver</exec_depend>
  <exec_depend>picknik_reset_fault_controller</exec_depend>

  <test_depend>ament_lint_auto</test_depend>

  <test_depend>ament_clang_format</test_depend>
  <test_depend>ament_clang_tidy</test_depend>
  <test_depend>ament_cmake_copyright</test_depend>
  <test_depend>ament_cmake_lint_cmake</test_depend>
  <test_depend>picknik_ament_copyright</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
